# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python3.10
repos:
- repo: https://github.com/ambv/black
  rev: 22.1.10
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort
